export type OperatingRoute = {
  id: string;
  path: string;
  number: string;
  label: string;
  section: "observe" | "analyze" | "prove" | "operate" | "learn";
  title: string;
  eyebrow: string;
  description: string;
  centerpiece: string;
  interaction: string;
  visualMode: "earth" | "dashboard" | "analysis" | "workspace" | "explorer" | "satellite" | "monitor" | "archive" | "dataset" | "model" | "workflow" | "evidence" | "spectral" | "fusion" | "timeline" | "mission" | "benchmark" | "report" | "alert" | "observatory" | "learning" | "settings" | "docs" | "judge" | "replay";
  boundary: string;
};

export const operatingRoutes: OperatingRoute[] = [
  { id: "landing", path: "/", number: "01", label: "Earth", section: "observe", title: "Ask anything. Understand Earth.", eyebrow: "SatQuery AI / SIH26167", description: "A cinematic, evidence-first entry to GeoSaarthi’s bounded Earth intelligence system.", centerpiece: "Orbital Earth and acquisition signal", interaction: "Enter command center or explore a demo mission", visualMode: "earth", boundary: "Supplied benchmark imagery; no live satellite feed." },
  { id: "dashboard", path: "/dashboard", number: "02", label: "Mission control", section: "observe", title: "Today’s intelligence, at a glance.", eyebrow: "Daily mission overview", description: "System readiness, recent analysis records, mission signals, and a direct AI command entry.", centerpiece: "Operations telemetry wall", interaction: "Open the latest mission or start a new analysis", visualMode: "dashboard", boundary: "System and satellite telemetry are explicitly simulated unless recorded run metadata is shown." },
  { id: "new-analysis", path: "/new-analysis", number: "03", label: "New analysis", section: "analyze", title: "Choose how Earth should be seen.", eyebrow: "Input relationship", description: "Start a single-image, bi-temporal, or optical–SAR analysis with visible requirements.", centerpiece: "Three observation contracts", interaction: "Select a workflow and move into validation", visualMode: "analysis", boundary: "Local raw image bytes remain in the browser workspace." },
  { id: "workspace", path: "/workspace", number: "04", label: "Analysis workspace", section: "analyze", title: "Turn imagery into inspectable evidence.", eyebrow: "Mission workspace", description: "Review imagery, ask a natural-language question, observe routing, and inspect the evidence package.", centerpiece: "Evidence-linked imagery canvas", interaction: "Control the active layer and run a bounded analysis", visualMode: "workspace", boundary: "Specialist results are scripted-demo or recorded prototype outputs." },
  { id: "earth", path: "/earth", number: "05", label: "Explore Earth", section: "observe", title: "Choose an area. Start a mission.", eyebrow: "Earth explorer", description: "Navigate benchmark sectors through layers, locations, and observation coverage.", centerpiece: "Area-of-interest globe surface", interaction: "Select an AOI and load its compatible demo", visualMode: "explorer", boundary: "Explorer locations and coverage are demo representations, not GIS coverage claims." },
  { id: "satellites", path: "/satellites", number: "06", label: "Live satellites", section: "observe", title: "Track the observation link.", eyebrow: "Mission simulation", description: "Inspect orbital tracks, instrument context, simulated telemetry, and next-pass views.", centerpiece: "Orbital pass field", interaction: "Select a pass to see its declared observation context", visualMode: "satellite", boundary: "Orbital position, pass, and telemetry displays are simulated." },
  { id: "monitor", path: "/monitor", number: "07", label: "Change monitor", section: "observe", title: "Watch Earth over time.", eyebrow: "Temporal monitoring", description: "Review monitored regions, temporal pairs, detected visual changes, and analyst attention states.", centerpiece: "Temporal change strip", interaction: "Compare an active region across time", visualMode: "monitor", boundary: "Change signals originate from scripted benchmark demonstrations." },
  { id: "analyses", path: "/analyses", number: "08", label: "My analyses", section: "analyze", title: "Return to any analysis record.", eyebrow: "Metadata archive", description: "Search, filter, and reopen persisted mission metadata without retaining raw imagery.", centerpiece: "Run history ledger", interaction: "Search a run and open its evidence trail", visualMode: "archive", boundary: "Only analysis metadata persists in the current prototype." },
  { id: "datasets", path: "/datasets", number: "09", label: "Datasets", section: "observe", title: "Know the source before the signal.", eyebrow: "Dataset explorer", description: "Inspect sample imagery, metadata, declared provenance, and the role each source plays in a mission.", centerpiece: "Provenance registry", interaction: "Preview a benchmark source and load a compatible mission", visualMode: "dataset", boundary: "Dataset descriptions are prototype references, not a complete data catalog." },
  { id: "models", path: "/models", number: "10", label: "Models & tools", section: "analyze", title: "See the specialist before it speaks.", eyebrow: "Registry", description: "Review model adapters, versioning, supported tasks, limitations, and licensing notes.", centerpiece: "Transparent model registry", interaction: "Inspect a specialist’s accepted inputs and known limits", visualMode: "model", boundary: "Readiness describes local prototype routing, not deployed production service health." },
  { id: "workflow", path: "/workflow", number: "11", label: "Workflow lab", section: "analyze", title: "Make the black box inspectable.", eyebrow: "Visual orchestration", description: "Follow the sequence from input to validation, routing, specialist selection, evidence, confidence, and answer.", centerpiece: "Execution graph", interaction: "Activate graph nodes to inspect their contract", visualMode: "workflow", boundary: "The graph describes the bounded implementation rather than hidden chain-of-thought." },
  { id: "evidence", path: "/evidence", number: "12", label: "Evidence center", section: "prove", title: "Inspect the proof, not just the answer.", eyebrow: "Evidence relationships", description: "Explore detected regions, visual masks, grounding references, overlays, and source links.", centerpiece: "Evidence relationship map", interaction: "Focus a region and compare the supporting layer", visualMode: "evidence", boundary: "Overlay regions are visual demo references, not calibrated geographical masks." },
  { id: "spectral", path: "/spectral", number: "13", label: "Spectral lab", section: "prove", title: "Read the scene through its bands.", eyebrow: "Band inspection", description: "Explore wavelength concepts, pixel inspection, spectral curves, and the limits of browser-side previews.", centerpiece: "Wavelength curve field", interaction: "Select a conceptual band or sample pixel", visualMode: "spectral", boundary: "Spectral curves are educational illustrations, not derived measurements from uploaded pixels." },
  { id: "fusion", path: "/fusion", number: "14", label: "Optical–SAR lab", section: "prove", title: "Use two sensors to see more.", eyebrow: "Cross-modal reasoning", description: "Compare optical and radar views, surface complementary cues, and inspect fusion workflow requirements.", centerpiece: "Dual-modality split canvas", interaction: "Move the fusion divider and inspect the reasoning path", visualMode: "fusion", boundary: "Fusion display is a scripted benchmark visualization, not live sensor fusion." },
  { id: "time-machine", path: "/time-machine", number: "15", label: "Time machine", section: "prove", title: "Put observations on the same timeline.", eyebrow: "Historical comparison", description: "Move through a before/after sequence, change map, and evidence timeline.", centerpiece: "Temporal acquisition rail", interaction: "Scrub dates and switch comparison modes", visualMode: "timeline", boundary: "Historical imagery dates belong to the scripted benchmark scenario." },
  { id: "missions", path: "/missions", number: "16", label: "Mission center", section: "operate", title: "Choose the question that matters.", eyebrow: "Mission library", description: "Review flood, urban, forest, coastal, agriculture, and disaster mission framings.", centerpiece: "Six mission sectors", interaction: "Open a mission brief and launch its demonstration", visualMode: "mission", boundary: "Mission categories are scenario templates for the SIH prototype." },
  { id: "benchmarks", path: "/benchmarks", number: "17", label: "Benchmark lab", section: "operate", title: "Test the route, reveal the boundary.", eyebrow: "Evaluation workspace", description: "Run benchmark cases, see workflow coverage, distinguish recorded metadata from scripted readiness, and review reproducibility.", centerpiece: "Benchmark coverage matrix", interaction: "Execute a case and inspect its trace", visualMode: "benchmark", boundary: "No unverified accuracy or latency claim is displayed as a real metric." },
  { id: "reports", path: "/reports", number: "18", label: "Report studio", section: "prove", title: "Turn a mission into an artifact.", eyebrow: "Evidence report", description: "Generate, preview, inspect, and export a concise evidence-first analysis record.", centerpiece: "Mission report artifact", interaction: "Review the report contract and export metadata", visualMode: "report", boundary: "Reports export validated prototype metadata and declared limitations." },
  { id: "alerts", path: "/alerts", number: "19", label: "Alert center", section: "operate", title: "Separate signals from urgency.", eyebrow: "Attention queue", description: "Review change, system, satellite, and model attention states with clear severity and resolution context.", centerpiece: "Analyst alert queue", interaction: "Filter alert type and inspect its evidence link", visualMode: "alert", boundary: "Alert items are demonstration states, not operational notifications." },
  { id: "observatory", path: "/observatory", number: "20", label: "System observatory", section: "operate", title: "Observe the system with the same rigor.", eyebrow: "Prototype observability", description: "Inspect local run counts, workflow coverage, health descriptors, latency boundaries, and storage policy.", centerpiece: "System signal lattice", interaction: "Explore a metric and its source boundary", visualMode: "observatory", boundary: "Infrastructure metrics are illustrative unless derived from recorded application metadata." },
  { id: "learn", path: "/learn", number: "21", label: "Learning center", section: "learn", title: "Learn how Earth becomes evidence.", eyebrow: "Remote-sensing primer", description: "Explore short practical lessons on optical, SAR, multispectral imagery, and AI-supported interpretation.", centerpiece: "Learning constellation", interaction: "Open a lesson and test a concept", visualMode: "learning", boundary: "Educational content is conceptual and does not replace domain review." },
  { id: "settings", path: "/settings", number: "22", label: "Settings", section: "operate", title: "Set the conditions for careful work.", eyebrow: "Workspace preferences", description: "Review appearance, accessibility, browser behavior, prototype retention policy, and account boundaries.", centerpiece: "Preference control plane", interaction: "Toggle local display and accessibility preferences", visualMode: "settings", boundary: "Account and retention controls are descriptive where server-managed support is not implemented." },
  { id: "help", path: "/help", number: "23", label: "Help & docs", section: "learn", title: "Follow the route from first scene to final report.", eyebrow: "Interactive documentation", description: "Read tutorials, workflow guides, keyboard commands, and the bounded API surface.", centerpiece: "Documentation route map", interaction: "Choose a guided workflow and open its relevant page", visualMode: "docs", boundary: "Documentation reflects the shipped prototype interfaces only." },
  { id: "judge", path: "/judge", number: "24", label: "Judge mode", section: "operate", title: "Demonstrate the complete proof chain.", eyebrow: "One-click SIH demonstration", description: "Launch a guided sequence through benchmark missions, execution trace, evidence, confidence, and report output.", centerpiece: "Five-step proof route", interaction: "Run a selected benchmark demonstration", visualMode: "judge", boundary: "Judge mode executes scripted benchmark flows and makes their boundaries visible." },
  { id: "replay", path: "/replay", number: "25", label: "Mission replay", section: "prove", title: "Replay every decision in order.", eyebrow: "Input to artifact", description: "Revisit input, validation, routing, model, evidence, answer, and report transitions as one inspectable route.", centerpiece: "Replay timeline", interaction: "Step forward and backward through an analysis sequence", visualMode: "replay", boundary: "Replay reflects available run metadata and scripted trace events only." },
];

export const operatingRouteById = Object.fromEntries(operatingRoutes.map((route) => [route.id, route])) as Record<string, OperatingRoute>;
export const operatingRouteByPath = Object.fromEntries(operatingRoutes.map((route) => [route.path, route])) as Record<string, OperatingRoute>;

export function isOperatingRoutePath(path: string) {
  return path in operatingRouteByPath;
}
